module 3 complete
anastasii27/gift-certificate-module-3 pull request #1
Opened 2020-11-17 13:56 UTC by anastasii27

2020-11-24 12:42 UTC, aolshevskiy requested changes
General notes:
1. Usage of hibernate specific features is prohibited per requirements. Please use EntityManager and other JPA interfaces only.
2. Root pom.xml is not under Git
Non conflicting requirements hold from previous modules:
1. Layers should be separate from each other. Not modules for entities
2. No unit tests just integration once again

2020-11-24 12:42 UTC, aolshevskiy commented on common/src/main/java/com/epam/esm/config/SpringConfig.java
> +    public DataSource dataSource() {
This not needed with Spring Boot.

2020-11-24 12:42 UTC, aolshevskiy commented on common/src/main/java/com/epam/esm/config/SpringConfig.java
> +    public LocalSessionFactoryBean sessionFactory() {
Not needed.

2020-11-24 12:42 UTC, aolshevskiy commented on common/src/main/java/com/epam/esm/config/SpringConfig.java
> +    public PlatformTransactionManager transactionManager() {
Not needed.

2020-11-24 12:42 UTC, aolshevskiy commented on common/src/main/java/com/epam/esm/model/Certificate.java
> +    private ZoneId createDateTimezone;
It's very rare requirement to store timezone in the database. Usually UTC is used except for special cases like time of some event that happens in some special timezoned context. Please reconsider if you really need timezone for your datetime types.

2020-11-24 12:42 UTC, aolshevskiy commented on common/src/main/java/com/epam/esm/model/Certificate.java
> +               joinColumns = { @JoinColumn(name = "giftCertificateId")},
Current consesus expects uniform naming convention for both column names and table names. Also current convention is to use snake case for the database. Spring Boot has such options.

2020-11-24 12:42 UTC, aolshevskiy commented on common/src/main/java/com/epam/esm/model/Order.java
> +    @NotAudited
Why do we need Envers here?

2020-11-24 12:42 UTC, aolshevskiy commented on giftcertificate/src/main/java/com/epam/esm/dto/CertificateDto.java
> +import org.springframework.hateoas.RepresentationModel;
This import is not used.

2020-11-24 12:42 UTC, aolshevskiy commented on giftcertificate/src/main/java/com/epam/esm/repository/CertificateRepositoryImpl.java
> +    private SessionFactory sessionFactory;
Please replace with EntityManager.

2020-11-24 12:42 UTC, aolshevskiy commented on giftcertificate/src/main/java/com/epam/esm/repository/SelectFilteredQuery.java
> +                .append(value)
This code is vulnerable to SQL injection. Please use SQL parameters.

2020-11-24 12:42 UTC, aolshevskiy commented on user/src/main/java/com/epam/esm/repository/UserRepositoryImpl.java
> +    private SessionFactory sessionFactory;
Please replace with EntityManager.

2020-11-24 17:49 UTC, natashlapakova commented on giftcertificate/src/test/java/com/epam/esm/service/CertificateServiceImplTest.java
> +
Mockito.doNothing() can be used instead

2020-12-01 16:35 UTC, dzmitrySazonov commented on common/src/main/java/com/epam/esm/audit/listener/CertificateListener.java
> +                certificate.getLastUpdateDate(), certificate.getLastUpdateDateTimezone(), certificate.getDuration()));
better to replace such multi-args constructors with builders

2020-12-02 11:27 UTC, merged